version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: nearbuy-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: nearbuy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nearbuy-app-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: nearbuy
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_MAX_CONNECTIONS: 20
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - /app/node_modules

volumes:
  postgres_data_dev:
    driver: local
